<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<RootNamespace>ToolHireSystem</RootNamespace>
		<AssemblyName>ToolHireSystem</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Core" Version="1.38.0" />
		<PackageReference Include="Azure.Identity" Version="1.11.3" />
		<PackageReference Include="EntityFramework" Version="6.4.4" />
		<PackageReference Include="Maikebing.System.Windows.Forms.DataVisualization" Version="5.0.1" />
		<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.60.3" />
		<PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.60.3" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.5.1" />
		<PackageReference Include="Microsoft.IdentityModel.Logging" Version="7.5.1" />
		<PackageReference Include="Microsoft.IdentityModel.Protocols" Version="7.5.1" />
		<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.5.1" />
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.5.1" />
		<PackageReference Include="System.Buffers" Version="4.5.1" />
		<PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
		<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="8.0.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.5.1" />
		<PackageReference Include="System.Memory" Version="4.5.5" />
		<PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
		<PackageReference Include="System.Security.AccessControl" Version="6.0.1" />
		<PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
		<PackageReference Include="System.Security.Permissions" Version="8.0.0" />
		<PackageReference Include="System.Security.Principal.Windows" Version="5.0.0" />
		<PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
		<PackageReference Include="System.Text.Json" Version="8.0.3" />
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
		<PackageReference Include="System.ValueTuple" Version="4.5.0" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Customer.cs" />
		<Compile Update="DBConnect.cs" />
		<Compile Update="FrmAddSupply.cs">
			
		</Compile>
		<Compile Update="FrmAddSupply.Designer.cs">
			<DependentUpon>FrmAddSupply.cs</DependentUpon>
		</Compile>
		<Compile Update="FrmTypeAnalysis.cs">
			
		</Compile>
		<Compile Update="FrmTypeAnalysis.Designer.cs">
			<DependentUpon>FrmTypeAnalysis.cs</DependentUpon>
		</Compile>
		<Compile Update="FrmCloseAccount.cs">
			
		</Compile>
		<Compile Update="FrmCloseAccount.Designer.cs">
			<DependentUpon>FrmCloseAccount.cs</DependentUpon>
		</Compile>
		<Compile Update="FrmMainMenu.cs">
		</Compile>
		<Compile Update="FrmMainMenu.Designer.cs">
			<DependentUpon>FrmMainMenu.cs</DependentUpon>
		</Compile>
		<Compile Update="FrmOpenAcc.cs">
		</Compile>
		<Compile Update="FrmOpenAcc.Designer.cs">
			<DependentUpon>FrmOpenAcc.cs</DependentUpon>
		</Compile>
		<Compile Update="FrmProcessRental.cs">
		</Compile>
		<Compile Update="FrmProcessRental.Designer.cs">
			<DependentUpon>FrmProcessRental.cs</DependentUpon>
		</Compile>
		<Compile Update="FrmRentalPayment.cs">
		</Compile>
		<Compile Update="FrmRentalPayment.Designer.cs">
			<DependentUpon>FrmRentalPayment.cs</DependentUpon>
		</Compile>
		<Compile Update="FrmReturnRental.cs">
		</Compile>
		<Compile Update="FrmReturnRental.Designer.cs">
			<DependentUpon>FrmReturnRental.cs</DependentUpon>
		</Compile>
		<Compile Update="FrmRevenueAnalysis.cs">
		</Compile>
		<Compile Update="FrmRevenueAnalysis.Designer.cs">
			<DependentUpon>FrmRevenueAnalysis.cs</DependentUpon>
		</Compile>
		<Compile Update="FrmUpdateAcc.cs">
		</Compile>
		<Compile Update="FrmUpdateAcc.Designer.cs">
			<DependentUpon>FrmUpdateAcc.cs</DependentUpon>
		</Compile>
		<Compile Update="Invoice.cs" />
		<Compile Update="Payment.cs" />
		<Compile Update="Program.cs" />
		<Compile Update="Properties\AssemblyInfo.cs" />
		<Compile Update="FrmRemoveSupply.cs">
		</Compile>
		<Compile Update="FrmRemoveSupply.Designer.cs">
			<DependentUpon>FrmRemoveSupply.cs</DependentUpon>
		</Compile>
		<Compile Update="Rental.cs" />
		<Compile Update="RentalItems.cs" />
		<Compile Update="Supply.cs" />
		<Compile Update="FrmUpdateSupply.cs">
		</Compile>
		<Compile Update="FrmUpdateSupply.Designer.cs">
			<DependentUpon>FrmUpdateSupply.cs</DependentUpon>
		</Compile>
		<Compile Update="User.cs" />
		<Compile Update="Validator.cs" />
		<EmbeddedResource Update="FrmAddSupply.resx">
			<DependentUpon>FrmAddSupply.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="FrmTypeAnalysis.resx">
			<DependentUpon>FrmTypeAnalysis.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="FrmCloseAccount.resx">
			<DependentUpon>FrmCloseAccount.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="FrmMainMenu.resx">
			<DependentUpon>FrmMainMenu.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="FrmOpenAcc.resx">
			<DependentUpon>FrmOpenAcc.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="FrmProcessRental.resx">
			<DependentUpon>FrmProcessRental.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="FrmRentalPayment.resx">
			<DependentUpon>FrmRentalPayment.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="FrmReturnRental.resx">
			<DependentUpon>FrmReturnRental.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="FrmRevenueAnalysis.resx">
			<DependentUpon>FrmRevenueAnalysis.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="FrmUpdateAcc.resx">
			<DependentUpon>FrmUpdateAcc.cs</DependentUpon>
		</EmbeddedResource>
		<Compile Update="Properties\Resources.Designer.cs">
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
			<DesignTime>True</DesignTime>
		</Compile>
		<EmbeddedResource Update="FrmRemoveSupply.resx">
			<DependentUpon>FrmRemoveSupply.cs</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="FrmUpdateSupply.resx">
			<DependentUpon>FrmUpdateSupply.cs</DependentUpon>
		</EmbeddedResource>
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
		<Compile Update="Properties\Settings.Designer.cs">
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
		</Compile>
		<None Update="ToolHireSystem_TemporaryKey.pfx" />
	</ItemGroup>
</Project>
