//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolHireSystem.Properties {

    // Cloud-ready configuration - static singleton removed for cloud compatibility
    // Settings are now loaded from environment variables and cloud configuration services
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {

        // Removed static singleton pattern for cloud-native architecture
        // Use dependency injection and IConfiguration instead

        // Temporary instance getter for backward compatibility during migration
        // TODO: Replace all Settings.Default usages with IConfiguration
        public static Settings Default {
            get {
                return new Settings();
            }
        }
    }
}
